---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-sample
  namespace: default
data:
  K8S_FOO: bar
  K8S_BAR: foo
---
apiVersion: v1
kind: Pod
metadata:
  name: env-sample
  namespace: default
spec:
  containers:
    - name: sample
      image: busybox
      command: [ "/bin/sh", "-c", "env" ]
      # One way - we expose all keys from the configMap as environment variables
      envFrom:
      - configMapRef:
          name: env-sample
      env:
        - name: K8S_FOO
          valueFrom:
            # Another way - use instruct what values from the configMap should be used for this key
            #   In that case it takes precedence and K8S_FOO will be equal to K8S_BAR's value
            configMapKeyRef:
              name: env-sample
              key: K8S_BAR
  restartPolicy: Never
